# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-leader
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: leader
        tier: backend
    spec:
      containers:
      - name: leader
        image: "docker.io/redis:6.0.5"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
  # Add the volumeMounts section
        volumeMounts:
        - mountPath: /data
          name: redis-storage
        # Add arguments to enable data persistence
        args: ["redis-server", "--appendonly", "yes"]
      # Add the volumes section
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc  # Reference the PVC